build: fix Deploy script

diff --git a/Deploy b/Deploy
--- a/Deploy
+++ b/Deploy
@@ -1,9 +1,3 @@
 #!/bin/sh
 
-if [ "$old_sum" != "$new_sum" ]; then
-    pnpm install
-    echo -n "$new_sum" > Deploy.cache
-fi
-
-# Build the react app
-pnpm run build && rm -r portfolio/ && mv build/ portfolio/ && echo "Deployed"
+pnpm install && pnpm run build && rm -r portfolio/ && mv build/ portfolio/ && echo "Deployed" || echo "Error"
